### ISSUE TITLE
error running split_libraries_fastq.py

### ISSUE THREAD

**Issue by pje1217** [ibiem-master/community#20]
Hello Josh, 

I am running my own dataset on the docker you helped me set up and I am having an issue when I run split_library_fastq.py

```{bash}
set -u
TAGDIR=$DEMUX_DIR/tagged_4
split_libraries_fastq.py -r 999 -n 999 -q 0 -p 0.0001 \
		--sequence_read_fps $RAW_FASTQ_DIR/5887-P1_S1_L001_R1_001.fastq.gz\
		--output_dir $TAGDIR \
		--barcode_read_fps $BARCODE_FASTQ \
		--mapping_fps $MAP_FILE \
		--phred_offset 33 \
		--barcode_type golay_12 \
		--rev_comp_mapping_barcodes \
		--store_demultiplexed_fastq \
		--retain_unassigned_reads
```

Traceback (most recent call last):
  File "/usr/local/bin/split_libraries_fastq.py", line 365, in <module>
    main()
  File "/usr/local/bin/split_libraries_fastq.py", line 347, in main
    fastq_writer(fasta_header, sequence, quality)
  File "/usr/local/bin/split_libraries_fastq.py", line 254, in fastq_writer
    output_fastq_f.write(format_fastq_record(h, s, q))
IOError: [Errno 28] No space left on device
close failed in file object destructor:
IOError: [Errno 28] No space left on device
close failed in file object destructor:
IOError: [Errno 28] No space left on device

This is the error I get but this is running on a virtual machine with enough space I believe. (The below is the info about the rapid VM virtual machine). Could you help me with this issue?

General Information
Hostname:
rapid-1125.vm.duke.edu
Operating System:
Ubuntu 18 Server
Base memory:
20 GB
Processors:
2
Extra info:
Request: https://clockworks.oit.duke.edu/vm_request/95168 Deployed from OVF packer-ubuntu-18.04-server-amd64(content version 2) on content library HPC 3 @ 2019-10-04 10:47:16 -0400
Console

**Comment by pje1217** [comment]
When I type "du -sh" in the terminal, it says 4.8G. Do you think my VM doesn't have enough space to process the data? The VM is supposed to have two processors, 20 GB RAM and 100 GB hard drive space.

**Comment by granek** [comment]
Sorry I missed this before.  I assume you understand why you are having this problem.
